name: Build and Release PDF-to-MD

on:
  push:
    tags:
      - "v*.*.*"   # 例如 v1.0.0 时才会触发构建

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4. 打包为 exe
      - name: Build exe
        run: |
          pyinstaller -F -w main.py
        shell: powershell

      # 5. 上传打包结果到 Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
